---
# title: "Education"
---
<div align="left" style="font-size:20px;line-height:2.5"> **Doctoral Studies** </div>

<p align="justify" style="font-size:16px;line-height:1.5;margin-bottom:18px">
In 2020, I commenced my doctoral studies at the Crawford School of Public Policy of the Australian National University under the supervision of Professor Warwick McKibbin, Professor Renee Fry-McKibbin, and Dr. Weifeng Liu.
</p>

<p align="justify" style="font-size:16px;line-height:1.5;margin-bottom:18px">
The commencement of my doctoral studies coincided with the outbreak of the COVID-19 pandemic. At three different stages of the pandemic, I conducted three studies with Professor McKibbin evaluating the economic consequences of the pandemic and public health and economic policy responses to it. The work culminated in three research papers and two book chapters. The papers have been cited in international media and institutional reports from international policy institutions. As of March 2025, the papers have been cited in over 4,000 publications (both academic papers and grey literature), according to Google Scholar.
</p>

<p align="justify" style="font-size:16px;line-height:1.5;margin-bottom:18px">
Since 2021, I studied the global economic impacts of climate risks. In April 2021, I co-authored a study with Professor McKibbin and Dr. Liu, evaluating the global economic impacts of physical (chronic and extreme risks), transition, and financial risks. From June to August 2022, for an internship at the Monetary and Capital Markets Department of the International Monetary Fund, I explored the systematic and unsystematic exposure of a global multisectoral sample of 59,554 firms to both chronic and extreme climate risks and their economic consequences. In June 2023, I received the Wallace E. Tyner award from the Global Trade Analysis Project (GTAP) for "being a promising young researcher undertaking policy-relevant research at the intersection of the economy, energy, and the environment", for my work on the global economic impacts of physical climate risks on agriculture and energy. Towards the late stage of my candidature, in 2024, I evaluated the impacts of physical climate risks on various financial assets.
</p>

<p align="justify" style="font-size:16px;line-height:1.5;margin-bottom:18px">
Since 2022, I studied the economic impacts of antimicrobial resistance (AMR). In June 2022, I co-authored a study with Professor McKibbin outlining a strategy to model the macroeconomic consequences of AMR. In November 2023, I released two studies exploring the interactions of physical climate risks and demographic trends with AMR. In June 2024, I co-authored a study with Professor McKibbin assessing the economic impacts of AMR.
</p>

<p align="justify" style="font-size:16px;line-height:1.5;margin-bottom:18px">
In June 2024, I submitted my PhD thesis, titled "Economic Impacts of COVID-19, Climate Change, and Antimicrobial Resistance". The thesis consisted of three chapters modeling the economic impacts of COVID-19 at different stages of the pandemic, four chapters exploring the physical, transition, and financial risks of climate change, and three chapters evaluating the interactions of AMR with climate change and demographic trends and thereby modeling the economic impacts of AMR. The thesis was accepted without corrections by the external reviewers, and the thesis is available from [the ANU Thesis Repository](https://openresearch-repository.anu.edu.au/items/172c0b36-16c7-45aa-8a6b-a2a5d0d3d1a7). I was awarded the PhD in December 2024.
</p>

<div align="left" style="font-size:20px;line-height:2.5"> **Postgraduate Studies leading to PhD** </div>

<p align="justify" style="font-size:16px;line-height:1.5;margin-bottom:18px">
In 2019, I obtained a master's in International and Development Economics, with Commendation, from the Crawford School of Public Policy. The essay I wrote for the course "Modeling the Global Economy", which was convened by Professor Warwick McKibbin, explored the global impact of the loss of confidence in Asian emerging markets. The study was published in The World Economy in 2020. My master's thesis, under the supervision of Professor McKibbin, assessed the global economic consequences of an escalation of AMR.
</p>

<p align="justify" style="font-size:16px;line-height:1.5;margin-bottom:18px">
In 2017, I obtained a master's in Financial Economics from the University of Colombo. One of the studies I conducted for Microeconomics explored the price elasticity of demand for pipe-borne water in Colombo, Sri Lanka, which is a prerequisite for resolving the water crisis there. The study was published in the OUSL Journal in 2018.
</p>

<p align="justify" style="font-size:16px;line-height:1.5;margin-bottom:18px">
Following the completion of the examinations at the Chartered Institute of Management Accountants (CIMA) of the UK in 2014, I obtained a master's in Business Administration from the University of West London in 2015. My thesis explored the factors affecting the economic affordability among domestic pipe-borne water consumers in Sri Lanka.
</p>

<div align="left" style="font-size:20px;line-height:2.5"> **Undergraduate Studies** </div>

<p align="justify" style="font-size:16px;line-height:1.5;margin-bottom:18px">
In 2017, I completed my undergraduate studies in Chemical and Process Engineering with a specialization in Environmental and Energy Engineering at the University of Moratuwa. My undergraduate research focused on optimizing biological wastewater treatment processes, and I received the "Excellence in Research" award from the Department of Chemical and Process Engineering for it.
</p>

<div style="text-align:center;margin-top:20px;"> <p>&copy; 2025 Roshen Fernando</p> </div>