---
# title: "Experience"
---
<div align = "left" style="font-size: 20px"> **Climate Change** </div>

<div align = "left" style="font-size: 18px"> **2022: Monetary and Capital Markets Department of the International Monetary Fund** </div>
<p align = "justify" style="font-size: 16px; line-height: 2; margin-bottom: 18px; list-style-type: none">
As a Summer Intern of the Fund Internship Program, from June to August 2022, I assessed how chronic and extreme physical climate risks could affect a global multisectoral sample of firms under alternative Shared Socioeconomic Pathways and the global macroeconomic consequences of those effects.
</p>

<div align = "left" style="font-size: 18px"> **2021/22: The Network for Greening the Financial System (NGFS)** </div>
<p align = "justify" style="font-size: 16px; line-height: 2; margin-bottom: 18px; list-style-type: none">
Along with Prof. Warwick McKibbin and Dr. Weifeng Liu, from September 2021 to June 2022, I evaluated the macroeconomic consequences of the NGFS climate policy scenarios in the multi-country and multi-sectoral G-Cubed model. Along with three groups of Integrate Assessment Modelers, we also compared the different modeling approaches and the policy insights from those differences.
</p>

<div align = "left" style="font-size: 18px"> **2021/22: The Australian Prudential Regulation Authority and the Australian Department of the Treasury** </div>
<p align = "justify" style="font-size: 16px; line-height: 2; margin-bottom: 18px; list-style-type: none">
Along with Prof. Warwick McKibbin and Dr. Weifeng Liu, from December 2021 to March 2022, I evaluated in-depth the macroeconomic consequences of the NGFS climate policy scenarios for Australian states and a wide array of economic sectors.
</p>

<div align = "left" style="font-size: 20px"> **Macroeconomic Nowcasting** </div>

<div align = "left" style="font-size: 18px"> **2021/22: The Asian Development Bank** </div>
<p align = "justify" style="font-size: 16px; line-height: 2; margin-bottom: 18px; list-style-type: none">
From November 2021 to March 2022, I constructed a suite of models for nowcasting the Gross Domestic Product of Sri Lanka. The model ensemble includes both conventional nowcasting models as well as modern machine learning algorithms.
</p>

<div style="text-align: center; margin-top: 20px;"> <p>&copy; 2023 Roshen Fernando</p> </div>