---
# title: "Roshen Fernando"
---
<div align = "center" style="font-size: 36px; line-height: 1.5; margin-top: 20px"> **ROSHEN FERNANDO** </div>

<!-- <div align = "center" style="font-size: 30px; line-height: 1.5"> *Demistifying Complexity* </div> -->

<div align = "left" style="font-size: 20px; line-height: 1.5; margin-bottom: 18px; margin-top: 10px"> A warm welcome to my personal page! </div>

<p align = "justify" style="font-size: 18px; line-height: 1.5; margin-bottom: 18px"> I am a final-year PhD Candidate from [the Crawford School of Public Policy](https://crawford.anu.edu.au/) of [the Australian National University](https://www.anu.edu.au/) (ANU). I am also associated with [the Centre for Applied Macroeconomic Analysis](https://cama.crawford.anu.edu.au/), [the Australian Research Council Centre of Excellence for Population Ageing Research](https://www.cepar.edu.au/), [the Institute for Climate, Energy & Disaster Solutions](https://iceds.anu.edu.au/), and [the Brookings Institution](https://www.brookings.edu/).
</p>

<p align = "justify" style="font-size: 18px; line-height: 1.5; margin-bottom: 18px"> I have been specializing in integrated modeling of the socioeconomic impacts of complex challenges to humanity. For my PhD research, I have been evaluating the economic consequences of infectious diseases (such as COVID-19), climate change, and antimicrobial resistance.
</p>

<p align = "justify" style="font-size: 18px; line-height: 1.5; margin-bottom: 18px"> My academic journey has been a dynamic fusion of economics, finance, management, and engineering. The diverse skill set I acquired from my education has driven me to conduct innovative analyses to capture how the interplay between natural and social systems contribute to those complex challenges and define their outcomes. I have also explored how these complex challenges could interact with each other. From my analyses, I have uncovered actionable insights to inform global policymaking, to improve industrial practices, and to drive positive change.
</p>

<p align = "justify" style="font-size: 18px; line-height: 1.5; margin-bottom: 18px"> As I transition to the next phase of my professional journey, I look forward to new opportunities to channel my expertise and experience to make a lasting impact on the world. Whether contribution to groundbreaking research, collaborations for transformative projects, or engagements with organizations committed to positive change, I am eagerly looking forward to challenges and triumphs that lie ahead.
</p>

<p align = "justify" style="font-size: 18px; line-height: 1.5; margin-bottom: 18px"> Thank you for visiting my page, and I invite you to explore my work, use them in your own if possible, and connect with me.
</p>

<div style="text-align: center; margin-top: 20px;"> <p>&copy; 2023 Roshen Fernando</p> </div>