---
# title: "Outreach"
---
<div align = "left" style="font-size: 20px"> **Conferences** </div>
<p align = "justify" style="font-size: 16px; line-height: 2; margin-bottom: 18px; list-style-type: none">
<span style="list-style-type: none;"> 
1. Economic Effects of the Climate Transition Policies of Brazil. First Annual Symposium of the Coalition for Capacity on Climate Action, Paris, 2-6 December 2024.
</span><br>
<span style="list-style-type: none;"> 
2. Global Economic Consequences of the Physical Climate Risks on Agriculture and Energy. International Conference on Big Data for Disaster Response Management in Asia and the Pacific, Sendai, 15-16 February 2024.
</span><br>
<span style="list-style-type: none;"> 
3. Global Economic Consequences of the Physical Climate Impacts on Agriculture and Energy. 12th South Asia Economic Policy Network Conference on Green Growth in South Asia, Dhaka, 30-31 October 2023.
</span><br>
<span style="list-style-type: none;"> 
4. Global Economic Impacts of Antimicrobial Resistance. 2nd International Conference of the Australian Research Council Centre of Excellence in Population Ageing Research, Sydney, 3-5 July 2023.
</span><br>
<span style="list-style-type: none;"> 
5. Global Economic Consequences Arising from the Impacts of Physical Climate Risks on Agriculture and Energy. 26th Annual Conference on Global Economic Analysis, Bordeaux, 14-16 June 2023.
</span><br>
<span style="list-style-type: none;"> 
6. Climate Risks and the Global Economy. Finance and the Macroeconomy Workshop, Canberra, 27 April 2023.
</span><br>
<span style="list-style-type: none;"> 
7. Global Economic Impacts of Physical Climate Risks. 16th International Forum on Financial Risks, Paris, 20-21 March 2023.
</span><br>
<span style="list-style-type: none;"> 
8. Implications of Physical Climate Risks on Health Conditions among Different Age Groups: Evidence from the Global Burden of Disease Data. Annual Workshop of Australian Research Council Centre of Excellence in Population Ageing Research, Sydney, 16-17 November 2022.
</span><br>
<span style="list-style-type: none;">
9. Infectious Diseases in a Life-cycle Economy. 19th National Conference of Emerging Researchers in Ageing, Melbourne, 4 November 2021.
</span><br>
<span style="list-style-type: none;">
10. Role of Demographic Trends in the Evolution of Antimicrobial Resistance: Initial Evidence. Annual Workshop of Australian Research Council Centre of Excellence in Population Ageing Research, Sydney, 2-3 November 2021.
</span><br>
<span style="list-style-type: none;"> 
11. Simulating the Effect of Modifying Reversed A2O Process on the Combined Removal of Nitrogen, Phosphorous, and Organic Matter in Municipal Wastewater. 111th Annual Sessions of Institute of Engineers Sri Lanka, Colombo, 23-24 October 2017.
</span><br>
<span style="list-style-type: none;"> 
12. Factors Affecting Economic Affordability among Consumers of the Domestic Water Sector in Sri Lanka. 7th International Conference on Water Resources & Environment Research, Kyoto, 6-8 June 2016.
</span><br>
<span style="list-style-type: none;"> 
13. Effective and Sustainable Utilization of Resources in Sri Lankan Industries: Challenges for and Benefits of an Integrated Approach. 6th Annual International Research Symposium on Engineering Advancements of South Asian Institute of Technology and Medicine, Colombo, 21-22 May 2016.
</p>

<div align = "left" style="font-size: 20px"> **Research Seminars** </div>
<p align = "justify" style="font-size: 16px; line-height: 2; margin-bottom: 18px; list-style-type: none">
<span style="list-style-type: none;"> 
1. Economic Effects of the Climate Transition Policies for Brazil. World Bank Model Talk Seminar Series, The World Bank, 19 November 2024.
</span><br>
<span style="list-style-type: none;">
2. Global Economic Impacts of Antimicrobial Resistance. Arndt-Corden Department of Economics Research Seminar Series, Crawford School of Public Policy, The Australian National University, 7 July 2023.
</span><br>
<span style="list-style-type: none;">
3. Global Economic Impacts of Physical Climate Risks. Arndt-Corden Department of Economics Research Seminar Series, Crawford School of Public Policy, The Australian National University, 31 March 2023.
</span><br>
<span style="list-style-type: none;"> 
4. Global Economic Impacts of Physical Climate Risks. QUANTM Seminar Series, Monetary and Capital Markets Department, The International Monetary Fund, 25 August 2022.
</span><br>
<span style="list-style-type: none;"> 
5. Global Economic Impacts of Climate Shocks and Changes in Climate Risk Assessment. QUANTM Seminar Series, Monetary and Capital Markets Department, The International Monetary Fund, 27 July 2022.
</span><br>
<span style="list-style-type: none;"> 
6. Tools for Monitoring Sri Lanka's Economy. Joint ERCD-SLRM Seminar, The Asian Development Bank, 11 April 2022.
</span><br>
<span style="list-style-type: none;"> 
7. Macroeconomic Consequences of COVID-19, Climate Change, and Antimicrobial Resistance. Arndt-Corden Department of Economics Research Seminar Series, Crawford School of Public Policy, The Australian National University, 13 August 2021.
</p>

<div align = "left" style="font-size: 20px"> **Invited Presentations** </div>
<p align = "justify" style="font-size: 16px; line-height: 2; margin-bottom: 18px; list-style-type: none">
<span style="list-style-type: none;"> 
1. Global Economic Impacts of Physical Climate Risks. European Central Bank Conference on Macroeconomic Modeling Frontiers for Research and Policy, Frankfurt, 28 November 2024.
</span><br>
<span style="list-style-type: none;">
2. Global Economic Impacts of Physical Climate Risks. Monash Business School Climate Workshop on Navigating the Energy Transition, Melbourne, 6 November 2023.
</p>

<div align = "left" style="font-size: 20px"> **Citations in National and International Reports** </div>
<p align = "justify" style="font-size: 16px; line-height: 2; margin-bottom: 18px; list-style-type: none">
<span style="list-style-type: none;"> 
1. Council of Economic Advisers & Office of Management & Budget of the Executive Office of the President of the United States, 2023, Methodologies and Considerations for Integrating the Physical and Transition Risks of Climate Change into Macroeconomic Forecasting for the President's Budget, March [(Link)](https://www.whitehouse.gov/wp-content/uploads/2023/03/CEA-OMB-White-Paper.pdf).
</span><br>
<span style="list-style-type: none;"> 
2. The International Monetary Fund, 2022, External Sector Report: Climate Policies and External Adjustment [(Link)](https://www.imf.org/-/media/Files/Publications/ESR/2022/English/ch2.ashx).
</span><br>
<span style="list-style-type: none;"> 
3. The Australian Research Council, 2021, Making a Difference: Outcomes of ARC Supported Research 2020-21, October [(Link)](https://online.flippingbook.com/view/237082075/).
</span><br>
<span style="list-style-type: none;"> 
4. The World Bank Group, 2021, Africa's Pulse, October [(Link)](https://documents1.worldbank.org/curated/en/786721633587328307/pdf/Africa-s-Pulse-No-24-October-2021-An-Analysis-of-Issues-Shaping-Africa-s-Economic-Future.pdf).
</span><br>
<span style="list-style-type: none;"> 
5. The World Bank Group, 2021, Global Economic Prospects, June [(Link)](https://openknowledge.worldbank.org/entities/publication/e70e9357-8459-5e9b-b069-97c0ad5a9769).
</span><br>
<span style="list-style-type: none;"> 
6. The World Bank Group, 2020, Global Economic Prospects, June [(Link)](https://openknowledge.worldbank.org/entities/publication/d29e6c95-4753-58e8-b368-d03c78cacab5)
</p>

<div align = "left" style="font-size: 20px"> **Research-based Articles in International Media** </div>
<p align = "justify" style="font-size: 16px; line-height: 2; margin-bottom: 18px; list-style-type: none">
<span style="list-style-type: none;"> 1. The first economic modeling of coronavirus scenarios is grim for Australia, the world (2020) (with Warwick McKibbin), The Conversation, 3 March [(Link)](https://theconversation.com/the-first-economic-modelling-of-coronavirus-scenarios-is-grim-for-australia-the-world-132759#comment_2162958).
</span>
</p>

<div align = "left" style="font-size: 20px"> **Research-based Media Commentaries** </div>
<p align = "justify" style="font-size: 16px; line-height: 2; margin-bottom: 18px; list-style-type: none">
<span style="list-style-type: none;">
1. Australia's commitment to Net Zero emissions and how will it impact us? (2021), Special Broadcasting Service (SBS) Sinhala, 4 November [(Link)](https://www.sbs.com.au/language/english/audio/australia-s-commitment-to-net-zero-emissions-and-how-will-it-impact-us).
</span><br>
<span style="list-style-type: none;">
2. What are the economic predictions for the Asia Pacific due to COVID-19? (2021), Special Broadcasting Service (SBS) Sinhala, 11 March [(Link)](https://www.sbs.com.au/language/english/audio/what-are-the-economic-predictions-for-asia-pacific-due-to-covid-19).
</span><br>
</p>

<div align = "left" style="font-size: 20px"> **Citations in International Media** </div>
<p align = "justify" style="font-size: 16px; line-height: 2; margin-bottom: 18px; list-style-type: none">
<span style="list-style-type: none;">
1. Long COVID for the global economy (2022), Top 1000 Funds, 13 January [(Link)](https://www.top1000funds.com/2022/01/long-covid-for-the-global-economy/).
</span><br>
<span style="list-style-type: none;">
2. Coronavirus recession looms, its course unrecognizable (2020), The New York Times, 21 March [(Link)](https://www.nytimes.com/2020/03/21/business/economy/coronavirus-recession.html).
</span><br>
<span style="list-style-type: none;">
3. Coronavirus will change how we shop, travel, and work for years (2020), Bloomberg, 14 March [(Link)](https://www.bloomberg.com/news/articles/2020-03-13/coronavirus-will-change-how-we-shop-travel-and-work-for-years).
</span><br>
<span style="list-style-type: none;">
4. The first economic modeling of coronavirus scenarios is grim for the world (2020), The Guardian, 3 March [(Link)](https://www.theguardian.com/australia-news/2020/mar/03/the-first-economic-modelling-of-coronavirus-scenarios-is-grim-for-the-world).
</span><br>
<span style="list-style-type: none;">
5. RBA slashes interest rates to a new low of 0.5pc to counter coronavirus hit (2020), Australian Broadcasting Corporation, 3 March [(Link)](https://www.abc.net.au/news/2020-03-03/reserve-bank-slashes-interest-rates-over-coronavirus/12020950).
</p>

<div style="text-align: center; margin-top: 20px;"> <p>&copy; 2025 Roshen Fernando</p> </div>